# `||` åˆ†éš”ç¬¦ä¹‹å‰æ˜¯é¡µé¢è·¯å¾„ï¼Œ`||` åˆ†éš”ç¬¦ä¹‹åæ˜¯å›¾æ ‡
# ç”¨æ³•ï¼ˆæœ‰å›¾æ ‡ï¼‰: `Key: /è·¯å¾„/ || fa(s|r|l|d|b) fa-å›¾æ ‡åç§°`
# ç”¨æ³•ï¼ˆæ— å›¾æ ‡ï¼‰: `Key: /è·¯å¾„/`
# fas far fal fad fab æ˜¯ FontAwesome 5.x ä¸­å›¾æ ‡çš„å‰ç¼€ï¼Œä½ éœ€è¦æ ¹æ®å…·ä½“å›¾æ ‡è‡ªè¡Œè®¾ç½®
# æŸ¥æ‰¾å›¾æ ‡åç§°ï¼Œè¯·è®¿é—®ï¼šhttps://fontawesome.com/icons
menu:
  home: / || fas fa-home
  archives: /archives/ || fas fa-folder-open
  categories: /categories/ || fas fa-layer-group
  # tags: /tags/ || fas fa-tags


header:
  enable: true
  show_on:
    # åœ¨æ–‡ç« é¡µé¢æ˜¯å¦æ˜¾ç¤ºç½‘ç«™é¡¶éƒ¨
    post: true
  # ç½‘ç«™é¡¶éƒ¨çš„é«˜åº¦ï¼ˆè®¾ç½®ä¸ºç™¾åˆ†æ•°ï¼Œè¡¨ç¤ºæ‰€å å±å¹•é«˜åº¦çš„ç™¾åˆ†æ¯”ã€‚æ”¯æŒæ‰€æœ‰ CSS é•¿åº¦å•ä½ï¼‰
  height: 100%
  # é¡¶éƒ¨èƒŒæ™¯å›¾ç‰‡
  bg_image:
    enable: true
    # å¡«å†™å›¾ç‰‡è·¯å¾„æˆ–é“¾æ¥
    url: https://images.pexels.com/photos/2835436/pexels-photo-2835436.jpeg?cs=srgb&dl=pexels-francesco-ungaro-2835436.jpg&fm=jpg
  # é¡¶éƒ¨èƒŒæ™¯å›¾çš„é®ç½©æ•ˆæœ
  mask:
    enable: true
    # é€æ˜åº¦ï¼ˆå–å€¼ï¼š0 ~ 1ï¼‰
    opacity: 0.5
  nav:
    # é¡¶éƒ¨å¯¼èˆªæ çš„é«˜åº¦ï¼ˆæ”¯æŒæ‰€æœ‰ CSS é•¿åº¦å•ä½ï¼‰
    height: 50px
    # å¯¼èˆªæ çš„èƒŒæ™¯é¢œè‰²ï¼ˆå¸é¡¶æ—¶ï¼‰
    bg_color: "#333"
  # æç¤ºå‘ä¸‹æ»šåŠ¨çš„å›¾æ ‡
  scroll_down_icon:
    enable: true
    # æŸ¥æ‰¾å›¾æ ‡åç§°ï¼Œè¯·è®¿é—®ï¼šhttps://fontawesome.com/icons
    name: fas fa-angle-down
    # æ˜¯å¦å¯ç”¨åŠ¨ç”»
    animation: true


author:
  enable: true
  # ä¾§è¾¹æ å¤´åƒ
  avatar:
    # å¡«å†™å›¾ç‰‡è·¯å¾„æˆ–é“¾æ¥
    url: https://github.com/formattedd/formattedd.github.io/raw/hexo/source/_posts/daily/mybaby/baby.png
    # æ˜¯å¦æ˜¾ç¤ºä¸ºåœ†å½¢
    rounded: true
    # å¤´åƒé€æ˜åº¦ï¼ˆå–å€¼ï¼š0 ~ 1ï¼‰
    opacity: 1
    # é¼ æ ‡ç»è¿‡æ—¶çš„åŠ¨ç”»ï¼Œå¯é€‰å€¼ï¼šturn æˆ– shake
    animation: turn
  # æ ¼è¨€ï¼ˆå¯ä»¥æ˜¯ä»»æ„ä¸€å¥æƒ³å†™çš„è¯ï¼‰
  motto: Good good study, day day Up !


footer:
  # èƒŒæ™¯å›¾ç‰‡
  bg_image:
    enable: true
    # å¡«å†™å›¾ç‰‡è·¯å¾„æˆ–é“¾æ¥
    url: https://images.pexels.com/photos/4210037/pexels-photo-4210037.jpeg?cs=srgb&dl=pexels-anastasia-shuraeva-4210037.jpg&fm=jpg
  # é®ç½©æ•ˆæœ
  mask:
    enable: true
    # é®ç½©é€æ˜åº¦ (å–å€¼: 0 ~ 1).
    opacity: 0.5
  # ç‰ˆæƒä¿¡æ¯
  copyright:
    enable: true
    # æ˜¾ç¤ºçš„æ–‡å­—ä¿¡æ¯ï¼Œä¾‹å¦‚ï¼šxxx All Rights Reserved
    # å¦‚æœä¸è®¾ç½®ï¼Œå°†æ˜¾ç¤º Hexo é…ç½®æ–‡ä»¶ä¸­ author é¡¹çš„å†…å®¹
    text: 2015
    # å¼€å§‹æ—¶é—´ï¼ˆå¦‚æœä¸è®¾ç½®ï¼Œå°†ä½¿ç”¨æœ€æ–°çš„å¹´ä»½ï¼‰
    since: 2021
    # ç»“æŸæ—¶é—´ï¼ˆå¦‚æœä¸è®¾ç½®ï¼Œå°†ä½¿ç”¨æœ€æ–°çš„å¹´ä»½ï¼‰
    end:
  # æ—¥æœŸå’Œç‰ˆæƒä¹‹é—´çš„å›¾æ ‡
  icon:
    enable: true
    # æŸ¥æ‰¾å›¾æ ‡åç§°ï¼Œè¯·è®¿é—®ï¼šhttps://fontawesome.com/icons
    name: fas fa-heart
    # å¿ƒè·³åŠ¨ç”»
    animation: false
    # è¯·ä½¿ç”¨åŒ…è£¹å€¼ï¼ˆæ”¯æŒæ‰€æœ‰ CSS é¢œè‰²å•ä½ï¼‰
    color: "#ff0000"
  # Hexo é“¾æ¥ï¼ˆPowered by Hexoï¼‰
  powered:
    enable: false
    # æ˜¾ç¤ºç‰ˆæœ¬å·ï¼ˆä¾‹å¦‚ï¼švX.X.Xï¼‰
    version: false
  # ä¸»é¢˜é“¾æ¥ï¼ˆTheme - Stunï¼‰
  theme:
    enable: true
    # æ˜¾ç¤ºç‰ˆæœ¬å·ï¼ˆä¾‹å¦‚ï¼švX.X.Xï¼‰
    version: false
  # å¤‡æ¡ˆä¿¡æ¯ï¼ˆåªæœ‰ä¸­å›½å¼€å‘è€…ä¼šç”¨åˆ°ï¼‰è¯¦æƒ…: http://www.miitbeian.gov.cn/
  beian:
    enable: false
    # å¤‡æ¡ˆ XXXXXXXX å·
    icp:
  # ä»»ä½•è‡ªå®šä¹‰æ–‡æœ¬ï¼Œæ”¯æŒ HTMLï¼ˆä¾‹å¦‚ï¼šæ‰˜ç®¡äº <a href="https://pages.github.com/" rel="noopener" target="_blank">Github Pages</a>ï¼‰
  custom:
    enable: false
    # è‡ªå®šä¹‰æ–‡æœ¬å†…å®¹
    text:

# `||` åˆ†éš”ç¬¦ä¹‹å‰æ˜¯å…·ä½“é“¾æ¥ï¼Œ`||` åˆ†éš”ç¬¦ä¹‹åæ˜¯å›¾æ ‡ã€‚
# ç”¨æ³•ï¼ˆæœ‰å›¾æ ‡ï¼‰: `Key: /è·¯å¾„/ || fa(s|r|l|d|b) fa-å›¾æ ‡åç§°`
# ç”¨æ³•ï¼ˆæ— å›¾æ ‡ï¼‰: `Key: /è·¯å¾„/`
# fas far fal fad fab æ˜¯ FontAwesome 5.x ä¸­å›¾æ ‡çš„å‰ç¼€ï¼Œä½ éœ€è¦æ ¹æ®å…·ä½“å›¾æ ‡è‡ªè¡Œè®¾ç½®ã€‚
# æŸ¥æ‰¾å›¾æ ‡åç§°ï¼Œè¯·è®¿é—®ï¼šhttps://fontawesome.com/icons
#
# å¦‚æœä½ æ‰¾ä¸åˆ°æƒ³è¦çš„å›¾æ ‡ï¼Œå¯ä»¥è€ƒè™‘ç”¨æ–‡å­—æ¥ä»£æ›¿å›¾æ ‡æ˜¾ç¤ºï¼Œç”¨æ³•ï¼š
# é€šè¿‡æ·»åŠ  `origin:` å‰ç¼€å³å¯æ˜¾ç¤ºæ–‡å­—ã€‚ä¾‹å¦‚ï¼š`origin:çŸ¥` ä¼šä»¥ `çŸ¥` ä»£æ›¿å›¾æ ‡æ˜¾ç¤ºã€‚
social:
  github: https://github.com/formattedd || fab fa-github
  Gmail: mailto:ycm76229@gmail.com || origin:Gmail
  google: / || fab fa-google
  twitter: / || fab fa-twitter
  youtube: / || fab fa-youtube

# ç¤¾äº¤é“¾æ¥çš„è®¾ç½®
social_setting:
  # æ˜¯å¦å¯ç”¨ç¤¾äº¤é“¾æ¥
  enable: true
  # æ˜¯å¦åªæ˜¾ç¤ºå›¾æ ‡
  icon_only: true


night_mode:
  enable: true
  # åˆ‡æ¢å¤œæ™šæ¨¡å¼çš„æŒ‰é’®
  button:
    # æŒ‰é’®å—çš„é¢œè‰²ï¼ˆè¯·ä½¿ç”¨å¼•å·åŒ…è£¹å€¼ï¼‰
    color: "#fafafa"
    # æŒ‰é’®çš„èƒŒæ™¯é¢œè‰²ï¼ˆè¯·ä½¿ç”¨å¼•å·åŒ…è£¹å€¼ï¼‰
    bg_color: "#8c8a8a"
  # ä»£è¡¨ç™½å¤©å’Œå¤œæ™šçš„å›¾æ ‡ï¼ˆç›®å‰ä»…æ”¯æŒæ–‡æœ¬å’Œ emojiï¼‰
  icon:
    dark: ğŸŒœ
    light: ğŸŒ


local_search:
  # æ˜¯å¦å¯ç”¨
  enable: true


pjax:
  enable: true
  # æ˜¯å¦åœ¨åˆ‡æ¢é¡µé¢æ—¶ï¼Œæ»šåŠ¨åˆ°é¡¶éƒ¨å¤§å›¾çš„åº•éƒ¨
  avoid_banner: false
  # ï¼ï¼å¦‚æœä½ ä¸äº†è§£å¦‚ä½•ä½¿ç”¨ï¼Œè¯·å¿½ç•¥ä¸‹é¢çš„é…ç½®é¡¹ï¼ˆé»˜è®¤å³å¯ï¼‰ï¼ï¼
  # ä¸‹é¢é…ç½®é¡¹çš„ç”¨æ³•ï¼Œè¯·å‚è§: https://github.com/MoOx/pjax/#options
  elements:
  selectors:
  switches:
  switchesOptions:
  history: true
  # å¦‚æœå¯ç”¨è¿™ä¸ªé…ç½®é¡¹ï¼Œå¿…é¡»è®¾ç½® `avoid_banner: false`
  scrollTo: false
  scrollRestoration: false
  cacheBust: false
  debug: false
  currentUrlFullReload: false
  timeout: 0

toc:
  enable: true
  # æ˜¯å¦è‡ªåŠ¨æ·»åŠ åˆ—è¡¨åºå·
  list_number: true
  # æ˜¯å¦æ–‡æœ¬æº¢å‡ºæ—¶æ¢è¡Œ
  # true : æ–‡æœ¬æº¢å‡ºæ—¶æ¢è¡Œ
  # false: æ–‡æœ¬æº¢å‡ºæ—¶ä¸æ¢è¡Œï¼Œæ˜¾ç¤ºæ¨ªå‘æ»šåŠ¨æ¡
  wrap: true
  # æ˜¯å¦å§‹ç»ˆå±•å¼€æ‰€æœ‰æ–‡ç« ç›®å½•
  # true ï¼šå§‹ç»ˆå±•å¼€
  # falseï¼šé»˜è®¤æŠ˜å ï¼Œæ»šåŠ¨åˆ°å¯¹åº”ä½ç½®æ—¶è‡ªåŠ¨å±•å¼€
  expand_all: false
  # ç”Ÿæˆç›®å½•æ—¶ï¼Œè§£æ `<h1~6>` çš„æœ€å°æ·±åº¦
  # ä½ å¯ä»¥åœ¨ Front-Matter ä¸­ï¼Œé€šè¿‡æ·»åŠ  `toc_min_depth` å±æ€§ï¼Œæ¥ä¸ºæŸç¯‡æ–‡ç« æŒ‡å®šè¯¥é…ç½®
  min_depth: 1
  # ç”Ÿæˆç›®å½•æ—¶ï¼Œè§£æ `<h1~6>` çš„æœ€å¤§æ·±åº¦
  # ä½ å¯ä»¥åœ¨ Front-Matter ä¸­ï¼Œé€šè¿‡æ·»åŠ  `toc_max_depth` å±æ€§ï¼Œæ¥ä¸ºæŸç¯‡æ–‡ç« æŒ‡å®šè¯¥é…ç½®
  max_depth: 6

busuanzi:
  # æ˜¯å¦å¯ç”¨
  enable: true
  # æ˜¯å¦åªæ˜¾ç¤ºå›¾æ ‡
  icon_only: false
  # ç»Ÿè®¡ç«™ç‚¹ UV æ•°é‡
  site_uv:
    enable: true
    # æŸ¥æ‰¾å›¾æ ‡åç§°ï¼Œè¯·è®¿é—®ï¼šhttps://fontawesome.com/icons
    icon: fas fa-user
  # ç»Ÿè®¡ç«™ç‚¹ PV æ•°é‡
  site_pv:
    enable: true
    # æŸ¥æ‰¾å›¾æ ‡åç§°ï¼Œè¯·è®¿é—®ï¼šhttps://fontawesome.com/icons
    icon: fas fa-eye
  # ç»Ÿè®¡æ¯ç¯‡æ–‡ç« çš„ PV æ•°é‡
  post_pv:
    enable: true
    # æŸ¥æ‰¾å›¾æ ‡åç§°ï¼Œè¯·è®¿é—®ï¼šhttps://fontawesome.com/icons
    icon: fas fa-eye


google_adsense:
  # æ˜¯å¦å¯ç”¨
  enable: true
  # å¡«å†™ä½ çš„ client-id
  client: ca-pub-2468168745293588
  # å¦‚æœå’Œä½  AdSense åµŒå…¥ä»£ç ä¸­çš„è„šæœ¬åœ°å€ä¸ä¸€æ ·ï¼Œè¯·æ›´æ¢
  js_src: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
